accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns=[
    url(r'^login/$',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'^signup/$',views.SignUp.as_view(),name='signup')
]

groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks')

]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships")
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

posts/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
from django.conf import settings
import misaka
from groups.models import Group
from django.contrib.auth import get_user_model
User=get_user_model()


class Post(models.Model):
    user=models.ForeignKey(User,related_name='posts')
    created_at=models.DateTimeField(auto_now=True)
    message=models.TextField()
    message_html=models.TextField(editable=False)
    group=models.ForeignKey(Group,related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html=misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering=['-created_at']
        unique_together=['user','message']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model=get_user_model()
        fields=('username','email','password1','password2')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Display Name:'
        self.fields['email'].label='Email Address'

posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
# Create your views here.
from . import forms

class SignUp(CreateView):
    form_class=forms.UserCreateForm
    success_url=reverse_lazy('login')
    template_name='accounts/signup.html'

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
# Create your views here.
from django.urls import reverse
from django.views import generic
from .models import Group,GroupMember

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields=('name','description')
    model=Group

class SingleGroup(generic.DetailView):
    model=Group

class ListGroup(generic.ListView):
    model=Group

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

simplesocial/views.py
from django.views.generic import TemplateView

class ThanksPage(TemplateView):
    template_name='thanks.html'

class TestPage(TemplateView):
    template_name='test.html'

class HomePage(TemplateView):
    template_name='index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <h1>Log In</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-default" name="" value="Login">

  </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-default" name="" value="Sign Up">

  </form>
</div>
{% endblock %}

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="row">
  {% block pregroup %}{% endblock %}
  {% block group_content %}{% endblock %}
  {% block postgroup %}{% endblock %}

</div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count:{{ group.members.count }}</h2>
<div class="container">
  {% if user in group.members.all %}
  <a href="{% url "groups:leave" slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>

  {% else %}
  <a href="{% url "groups:join" slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span>Join</a>
  {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count==0 %}
  <h2>No posts in this group yet!</h2>
  {% else %}
  {% for post in group.posts.all %}
  {% include "posts/_post.html" %}
  {% endfor %}
{% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Simple Social</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

   <!-- Optional theme -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


   <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

   <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
       			<div class="container">

               <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

       					<ul class="nav navbar-nav navbar-right">
       						{% if user.is_authenticated %}
                         <li><a href="#" class="btn btn-simple">Post</a></li>
                         <li><a href="#" class="btn btn-simple">Groups</a></li>
                         <li><a href="#" class="btn btn-simple">Create Group</a></li>
                         <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
       						{% else %}
       						      <li><a href="#"class="btn btn-simple">Groups</a></li>
       						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
       						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
       						{% endif %}
       					</ul>
              </div>
       		</nav>


<div class="container">
  {% block content %}
  {% endblock %}
</div>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to Star Social! </h1>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting,come back soon!</h1>
{% endblock %}